server:
  port: 8888

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        #服务提供者路由 port:8701
        - id: hello_routh #路由的id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8701 #匹配后提供的路由地址
          uri: lb://hello-service #匹配后提供服务的路由地址
          predicates:
            - Path=/hello/**,/configInfo/** #断言，路径相匹配进行路由
        #服务调用者路由 port:8702
        - id: consumer_routh
          uri: lb://helloconsumer
          predicates:
            - Path=/consumer/**
            #- After=2020-08-18T12:00:00.485+08:00[Asia/Shanghai] #路由开启的时间范围
            #- Cookie=username,ygy #只有cookie包含username，并且value是ygy的才可以路由
            #- Header=X-Request-Id,\d+ #包含请求头的请求，才可以路由，属性名和正则表达式，属性值和正则匹配则执行
            #- Host=**.somehost.org,**.anotherhost.org
            #- Method=GET
            #- Query=username,\d+ #要有参数名username并且值是整数，如localhost：8080?username=123
#当访问localhost:9527/hello/ygy 时，
#路由到localhost：8701/hello/ygy
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8700/eureka

