age: 18
aaa: AAA
context: "aa: ${aaa},age: ${age}"

boy:
    age: 25
    height: 185


spring:
    servlet:
        multipart:
            enabled: true
            max-file-size: 20MB
            max-request-size: 20MB
    datasource:
        url: jdbc:mysql://192.168.133.176:3306/spring4
        username: gcj_admin
        password: test
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        connectionProperties: druid.stat.mergeSql=true
mybatis:
    type-aliases-package: com.glodon.springboothello.domain
    mapper-locations: classpath:mapper/*.xml