package com.ygy.mybatisdemo.domain;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookId
     *
     * @mbggenerated
     */
    private Integer bookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookname
     *
     * @mbggenerated
     */
    private String bookname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookpage
     *
     * @mbggenerated
     */
    private Integer bookpage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookisbn
     *
     * @mbggenerated
     */
    private String bookisbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookstatus
     *
     * @mbggenerated
     */
    private Integer bookstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookId
     *
     * @return the value of book.bookId
     *
     * @mbggenerated
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookId
     *
     * @param bookid the value for book.bookId
     *
     * @mbggenerated
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookname
     *
     * @return the value of book.bookname
     *
     * @mbggenerated
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookname
     *
     * @param bookname the value for book.bookname
     *
     * @mbggenerated
     */
    public void setBookname(String bookname) {
        this.bookname = bookname == null ? null : bookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookpage
     *
     * @return the value of book.bookpage
     *
     * @mbggenerated
     */
    public Integer getBookpage() {
        return bookpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookpage
     *
     * @param bookpage the value for book.bookpage
     *
     * @mbggenerated
     */
    public void setBookpage(Integer bookpage) {
        this.bookpage = bookpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookisbn
     *
     * @return the value of book.bookisbn
     *
     * @mbggenerated
     */
    public String getBookisbn() {
        return bookisbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookisbn
     *
     * @param bookisbn the value for book.bookisbn
     *
     * @mbggenerated
     */
    public void setBookisbn(String bookisbn) {
        this.bookisbn = bookisbn == null ? null : bookisbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookstatus
     *
     * @return the value of book.bookstatus
     *
     * @mbggenerated
     */
    public Integer getBookstatus() {
        return bookstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookstatus
     *
     * @param bookstatus the value for book.bookstatus
     *
     * @mbggenerated
     */
    public void setBookstatus(Integer bookstatus) {
        this.bookstatus = bookstatus;
    }

    @Override
    public String toString() {
        return "Book{" +
                "bookid=" + bookid +
                ", bookname='" + bookname + '\'' +
                ", bookpage=" + bookpage +
                ", bookisbn='" + bookisbn + '\'' +
                ", bookstatus=" + bookstatus +
                '}';
    }
}