package com.ygy.mybatisdemo.domain;

import java.util.Date;

public class Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.recordid
     *
     * @mbggenerated
     */
    private Integer recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.bookid
     *
     * @mbggenerated
     */
    private Integer bookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.orderdate
     *
     * @mbggenerated
     */
    private Date orderdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.lenddate
     *
     * @mbggenerated
     */
    private Date lenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.orderdeadline
     *
     * @mbggenerated
     */
    private Date returndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.lenddeadline
     *
     * @mbggenerated
     */
    private Date lenddeadline;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.recordid
     *
     * @return the value of record.recordid
     *
     * @mbggenerated
     */
    public Integer getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.recordid
     *
     * @param recordid the value for record.recordid
     *
     * @mbggenerated
     */
    public void setRecordid(Integer recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.userid
     *
     * @return the value of record.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.userid
     *
     * @param userid the value for record.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.bookid
     *
     * @return the value of record.bookid
     *
     * @mbggenerated
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.bookid
     *
     * @param bookid the value for record.bookid
     *
     * @mbggenerated
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.orderdate
     *
     * @return the value of record.orderdate
     *
     * @mbggenerated
     */
    public Date getOrderdate() {
        return orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.orderdate
     *
     * @param orderdate the value for record.orderdate
     *
     * @mbggenerated
     */
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.lenddate
     *
     * @return the value of record.lenddate
     *
     * @mbggenerated
     */
    public Date getLenddate() {
        return lenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.lenddate
     *
     * @param lenddate the value for record.lenddate
     *
     * @mbggenerated
     */
    public void setLenddate(Date lenddate) {
        this.lenddate = lenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.orderdeadline
     *
     * @return the value of record.orderdeadline
     *
     * @mbggenerated
     */
    public Date getReturndate() {
        return returndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.orderdeadline
     *
     * @param returndate the value for record.orderdeadline
     *
     * @mbggenerated
     */
    public void setReturndate(Date returndate) {
        this.returndate = returndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.lenddeadline
     *
     * @return the value of record.lenddeadline
     *
     * @mbggenerated
     */
    public Date getLenddeadline() {
        return lenddeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.lenddeadline
     *
     * @param lenddeadline the value for record.lenddeadline
     *
     * @mbggenerated
     */
    public void setLenddeadline(Date lenddeadline) {
        this.lenddeadline = lenddeadline;
    }

    @Override
    public String toString() {
        return "Record{" +
                "recordid=" + recordid +
                ", userid=" + userid +
                ", bookid=" + bookid +
                ", orderdate=" + orderdate +
                ", lenddate=" + lenddate +
                ", orderdeadline=" + returndate +
                ", lenddeadline=" + lenddeadline +
                '}';
    }
}